server:
  port: 8081
spring:
  application:
    name: utils-service
eureka:
  client:
    service-url:
     defaultZone: http://user:pass@localhost:8761/eureka/
  instance:
    prefer-ip-address: true